nome = input("scrivimi il percorso dove posso trovare il file  ")
print (nome)
f = open(nome,"r")
stringami = f.read()
strippami = stringami.split()
datami = list(map(float,strippami))
datami.sort()
print(datami)
datami.sort(reverse = True)
print(datami)
