nome = input("scrivimi il percorso dove posso trovare il file  ")
print (nome)
f = open(nome,"r")
stringami = f.read()
strippami = stringami.split()
datami = list(map(float,strippami))
print("il massimo assoluto vale ", max(datami))
print("il minimo assoluto vale ", min(datami))
