nome = input("scrivimi il percorso dove posso trovare il file  ")
print (nome)
f = open(nome,"r")
stringami = f.read()
strippami = stringami.split()
datami = list(map(float,strippami))
datami.sort()
print("il massimo assoluto vale ", datami[len(datami)-1])
print("il minimo assoluto vale ", datami[0])
