nome = input("scrivimi il percorso dove posso trovare il file  ")
print (nome)
f = open(nome,"r")
stringami = f.read()
strippami = stringami.split()
datami = list(map(float,strippami))
print("il vettore è lungo", len (datami))
print("la somma vale ", sum(datami))
print("il valore medio vale ", sum(datami)/len(datami))
